CREATE TABLE activities
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    backlog_item_id INTEGER                     NOT NULL,
    activity_date   TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    type            VARCHAR                     NOT NULL,
    from_status     VARCHAR,
    to_status       VARCHAR,
    PRIMARY KEY (id),
    FOREIGN KEY (backlog_item_id)
        REFERENCES backlog_items (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
