CREATE TABLE backlogs
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (title_id)
        REFERENCES titles (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
