CREATE TABLE activities
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    activity_type VARCHAR                     NOT NULL,
    activity_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
    title_id      INTEGER                     NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (title_id)
        REFERENCES titles (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX ON activities (activity_date DESC);
