name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Java
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            frontend/node
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Cache Node repository
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package.json') }}
          restore-keys: ${{ runner.os }}-node
      - name: Build and test
        run: mvn verify -B
